# Generated by Django 2.2.6 on 2019-10-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirconType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircon_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Aircon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.IntegerField()),
                ('model_number', models.CharField(max_length=255)),
                ('aircon_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.AirconType')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.ModelType')),
            ],
        ),
    ]
